version: '3.9'

services:
  db:
    build:
      context: postgres/.
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=kmw
      - POSTGRES_PASSWORD=bald
    ports:
      - "5432:5432"
    volumes:
      - twitch_db:/var/lib/postgresql/data
    networks:
      - lognet
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 256M
    
  twitch-chat-listener:
    build:
      context: twitch-chat-listener/.
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/code"
    depends_on:
      - db
    networks:
      - lognet
    deploy:
      resources:
        limits:
          cpus: 1
          memory: 256M

networks:
  lognet:
    driver: bridge

volumes:
  twitch_db:
    driver: local
