version: '3.9'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - lognet

  app:
    container_name: twitch-chat-listener
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ".:/code"
    depends_on:
      - redis
    networks:
      - lognet

networks:
  lognet:
    driver: bridge